upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 20M;

    # فایل‌های static (css, js, admin panel assets)
    location /static/ {
        alias /app/staticfiles/;
    }

    # فایل‌های media (عکس‌هایی که از پنل ادمین آپلود می‌شن)
    location /media/ {
        alias /app/media/;
    }

    # بقیه‌ی درخواست‌ها بره سمت جنگو/gunicorn
    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
