# Generated by Django 5.2.6 on 2025-12-05 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد کوپن')),
                ('valid_from', models.DateTimeField(verbose_name='تاریخ شروع اعتبار')),
                ('valid_to', models.DateTimeField(verbose_name='تاریخ پایان اعتبار')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپن\u200cها',
                'ordering': ['-valid_from'],
            },
        ),
    ]
