# Generated by Django 5.2.6 on 2025-09-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='آیا محصول ویژه است؟', verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='آیا محصول موجود است؟', verbose_name='موجود'),
        ),
    ]
