# Generated by Django 5.2.6 on 2025-09-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_featured_alter_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='آیا دسته بندی ویژه است؟', verbose_name='ویژه'),
        ),
    ]
