# Generated by Django 5.2.6 on 2025-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='آیا دسته بندی ویژه است؟', verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='آیا محصول ویژه است؟', verbose_name='ویژه'),
        ),
    ]
