# Generated by Django 5.2.6 on 2025-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_is_featured_alter_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='آیا این دسته بندی ویژه است؟', verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='آیا این محصول موجود است؟', verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='آیا این محصول ویژه است؟', verbose_name='ویژه'),
        ),
    ]
