# Generated by Django 5.2.6 on 2025-09-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='درصد تخفیف'),
        ),
    ]
