# Generated by Django 5.2.6 on 2025-11-24 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=70, verbose_name='LastName')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=12, verbose_name='PhoneNumber')),
                ('address_line1', models.TextField(verbose_name='AddressLine1')),
                ('address_line2', models.TextField(verbose_name='AddressLine2')),
                ('postal_code', models.IntegerField(verbose_name='PostalCode')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('is_billing', models.BooleanField(verbose_name='OriginAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
